name: Push NAV for DeTrade Core WETH

on:
  push:
    branches:
      - main
  # schedule:
  #   - cron: '0 * * * *'  # Runs every hour
  workflow_dispatch:  # Allows manual triggering

jobs:
  run-pusher:
    runs-on: ubuntu-latest
    env:
      ETHEREUM_RPC: ${{ secrets.ETHEREUM_RPC }}
      BASE_RPC: ${{ secrets.BASE_RPC }}
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run pusher
      env:
        MONGO_URI: ${{ secrets.MONGO_URI }}
        DATABASE_NAME: ${{ secrets.DATABASE_NAME }}
        COLLECTION_NAME: ${{ secrets.COLLECTION_NAME }}
      run: python -m builder.pusher 